#!/usr/bin/env bash
# Install πD.app → /Applications + ~/Applications
# Bakes absolute node/npm paths so Dock launch matches Terminal.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Capture Terminal-visible Node into a file the GUI app can source
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.volta/bin:$PATH"
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
# shellcheck disable=SC1091
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh" 2>/dev/null || true
command -v fnm >/dev/null 2>&1 && eval "$(fnm env)" 2>/dev/null || true
if ! command -v node >/dev/null 2>&1 && [[ -d "$HOME/.nvm/versions/node" ]]; then
  L=$(ls -1 "$HOME/.nvm/versions/node" 2>/dev/null | tail -1 || true)
  [[ -n "$L" ]] && export PATH="$HOME/.nvm/versions/node/$L/bin:$PATH"
fi

NODE_BIN="$(command -v node || true)"
NPM_BIN="$(command -v npm || true)"
PATHS_FILE="$ROOT/scripts/.mac-paths.sh"

if [[ -n "$NODE_BIN" ]]; then
  cat >"$PATHS_FILE" <<EOF
# Auto-generated by npm run install:app — do not edit
export PATH="$(dirname "$NODE_BIN"):\$PATH"
export PID_NODE="$NODE_BIN"
export PID_NPM="${NPM_BIN:-npm}"
EOF
  echo "baked node path: $NODE_BIN"
else
  rm -f "$PATHS_FILE"
  echo "warning: node not in PATH while installing — Dock app may fail until Node is installed"
fi

chmod +x "$ROOT/scripts/mac-app-run.sh" "$ROOT/scripts/launch.sh" "$ROOT/πD.command" 2>/dev/null || true

install_one() {
  local APP_DIR="$1"
  local MACOS_DIR="$APP_DIR/Contents/MacOS"
  local RES_DIR="$APP_DIR/Contents/Resources"
  local BIN="$MACOS_DIR/piD"

  rm -rf "$APP_DIR"
  mkdir -p "$MACOS_DIR" "$RES_DIR"

  # Thin trampoline → mac-app-run.sh (logs + PATH + alerts)
  cat >"$BIN" <<EOF
#!/bin/bash
exec /bin/bash "$ROOT/scripts/mac-app-run.sh"
EOF
  chmod +x "$BIN"

  # Icon
  local ICNS="$RES_DIR/AppIcon.icns"
  local PNG_SRC=""
  for c in \
    "$ROOT/public/icon-1024.png" \
    "$ROOT/public/icon-512.png" \
    "$ROOT/public/apple-touch-icon.png" \
    "$ROOT/public/icon-256.png"
  do
    [[ -f "$c" ]] && PNG_SRC="$c" && break
  done

  if [[ -n "$PNG_SRC" ]] && command -v sips >/dev/null 2>&1 && command -v iconutil >/dev/null 2>&1; then
    local TMPD ICONSET
    TMPD="$(mktemp -d)"
    ICONSET="$TMPD/AppIcon.iconset"
    mkdir -p "$ICONSET"
    for sz in 16 32 128 256 512; do
      sips -z "$sz" "$sz" "$PNG_SRC" --out "$ICONSET/icon_${sz}x${sz}.png" >/dev/null 2>&1 || true
      sips -z $((sz * 2)) $((sz * 2)) "$PNG_SRC" --out "$ICONSET/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1 || true
    done
    iconutil -c icns "$ICONSET" -o "$ICNS" 2>/dev/null || true
    rm -rf "$TMPD"
  fi
  [[ -n "$PNG_SRC" ]] && cp "$PNG_SRC" "$RES_DIR/icon.png" 2>/dev/null || true

  cat >"$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>piD</string>
  <key>CFBundleIdentifier</key>
  <string>local.pid.board</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>πD</string>
  <key>CFBundleDisplayName</key>
  <string>πD</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>5</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>LSBackgroundOnly</key>
  <false/>
</dict>
</plist>
PLIST

  echo -n "APPLPID1" >"$APP_DIR/Contents/PkgInfo"

  xattr -cr "$APP_DIR" 2>/dev/null || true
  local LSREG="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
  [[ -x "$LSREG" ]] && "$LSREG" -f -R "$APP_DIR" 2>/dev/null || true

  # Smoke-test the trampoline the same way Dock does (minimal env)
  env -i HOME="$HOME" USER="$USER" TMPDIR="${TMPDIR:-/tmp}" LOGNAME="${LOGNAME:-$USER}" \
    /bin/bash "$BIN" && echo "smoke-test OK for $APP_DIR" || echo "smoke-test returned $? (check /tmp/pid-app.log)"

  echo "installed → $APP_DIR"
}

# Clean old installs
rm -rf "/Applications/πD.app" "$HOME/Applications/πD.app" 2>/dev/null || true

if [[ -n "${PID_APP_DIR:-}" ]]; then
  mkdir -p "$(dirname "$PID_APP_DIR")"
  install_one "$PID_APP_DIR"
else
  # /Applications
  if [[ -w /Applications ]]; then
    install_one "/Applications/πD.app"
  else
    TMP="$(mktemp -d)/πD.app"
    install_one "$TMP"
    if cp -R "$TMP" /Applications/πD.app 2>/dev/null; then
      echo "copied to /Applications/πD.app"
    else
      echo "Need password to install into /Applications…"
      osascript -e "do shell script \"rm -rf /Applications/πD.app; cp -R '$TMP' /Applications/πD.app; xattr -cr /Applications/πD.app\" with administrator privileges" 2>/dev/null \
        && echo "installed → /Applications/πD.app" \
        || echo "skipped /Applications (no permission) — using ~/Applications only"
    fi
    rm -rf "$(dirname "$TMP")"
  fi
  mkdir -p "$HOME/Applications"
  install_one "$HOME/Applications/πD.app"
fi

# Also drop a double-clickable command next to project
cp "$ROOT/scripts/mac-app-run.sh" "$ROOT/πD.command" 2>/dev/null || true
chmod +x "$ROOT/πD.command" 2>/dev/null || true

echo ""
echo "Try:"
echo "  open /Applications/πD.app"
echo "  open \"\$HOME/Applications/πD.app\""
echo ""
echo "If Dock still fails:"
echo "  cat /tmp/pid-app.log"
echo "project: $ROOT"
echo "node: ${NODE_BIN:-not found}"
