#!/usr/bin/env bash
# Install πD.app → /Applications + ~/Applications
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.volta/bin:$PATH"
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
# shellcheck disable=SC1091
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh" 2>/dev/null || true
command -v fnm >/dev/null 2>&1 && eval "$(fnm env)" 2>/dev/null || true
if ! command -v node >/dev/null 2>&1 && [[ -d "$HOME/.nvm/versions/node" ]]; then
  L=$(ls -1 "$HOME/.nvm/versions/node" 2>/dev/null | tail -1 || true)
  [[ -n "$L" ]] && export PATH="$HOME/.nvm/versions/node/$L/bin:$PATH"
fi

NODE_BIN="$(command -v node || true)"
NPM_BIN="$(command -v npm || true)"
PATHS_FILE="$ROOT/scripts/.mac-paths.sh"

mkdir -p "$HOME/Library/Logs"

if [[ -n "$NODE_BIN" ]]; then
  cat >"$PATHS_FILE" <<EOF
# Auto-generated by npm run install:app — $(date)
export PATH="$(dirname "$NODE_BIN"):\$PATH"
export PID_NODE="$NODE_BIN"
export PID_NPM="${NPM_BIN:-npm}"
EOF
  echo "baked node: $NODE_BIN"
else
  rm -f "$PATHS_FILE"
  echo "WARNING: node not found in this Terminal. Install Node from nodejs.org first."
fi

chmod +x "$ROOT/scripts/mac-app-run.sh" "$ROOT/scripts/launch.sh" 2>/dev/null || true

install_one() {
  local APP_DIR="$1"
  local MACOS_DIR="$APP_DIR/Contents/MacOS"
  local RES_DIR="$APP_DIR/Contents/Resources"
  local BIN="$MACOS_DIR/piD"

  rm -rf "$APP_DIR"
  mkdir -p "$MACOS_DIR" "$RES_DIR"

  # Trampoline — absolute path to mac-app-run.sh
  cat >"$BIN" <<EOF
#!/bin/bash
# πD.app entry — logs to ~/Library/Logs/piD.log
echo "trampoline \$(date)" >> "\$HOME/Library/Logs/piD.log" 2>/dev/null
echo "trampoline \$(date)" >> "\$HOME/piD-launch.log" 2>/dev/null
exec /bin/bash "$ROOT/scripts/mac-app-run.sh"
EOF
  chmod +x "$BIN"

  # Icon
  local ICNS="$RES_DIR/AppIcon.icns" PNG_SRC=""
  for c in "$ROOT/public/icon-1024.png" "$ROOT/public/icon-512.png" "$ROOT/public/apple-touch-icon.png" "$ROOT/public/icon-256.png"; do
    [[ -f "$c" ]] && PNG_SRC="$c" && break
  done
  if [[ -n "$PNG_SRC" ]] && command -v sips >/dev/null 2>&1 && command -v iconutil >/dev/null 2>&1; then
    local TMPD ICONSET
    TMPD="$(mktemp -d)"
    ICONSET="$TMPD/AppIcon.iconset"
    mkdir -p "$ICONSET"
    for sz in 16 32 128 256 512; do
      sips -z "$sz" "$sz" "$PNG_SRC" --out "$ICONSET/icon_${sz}x${sz}.png" >/dev/null 2>&1 || true
      sips -z $((sz*2)) $((sz*2)) "$PNG_SRC" --out "$ICONSET/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1 || true
    done
    iconutil -c icns "$ICONSET" -o "$ICNS" 2>/dev/null || true
    rm -rf "$TMPD"
    cp "$PNG_SRC" "$RES_DIR/icon.png" 2>/dev/null || true
  fi

  cat >"$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>piD</string>
  <key>CFBundleIdentifier</key>
  <string>local.pid.board</string>
  <key>CFBundleName</key>
  <string>πD</string>
  <key>CFBundleDisplayName</key>
  <string>πD</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>6</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>
PLIST
  printf 'APPLPID1' >"$APP_DIR/Contents/PkgInfo"

  xattr -cr "$APP_DIR" 2>/dev/null || true
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP_DIR" 2>/dev/null || true

  echo "installed → $APP_DIR"
}

rm -rf "/Applications/πD.app" "$HOME/Applications/πD.app" 2>/dev/null || true

if [[ -w /Applications ]]; then
  install_one "/Applications/πD.app"
else
  TMP="$(mktemp -d)/πD.app"
  install_one "$TMP"
  if ! cp -R "$TMP" /Applications/πD.app 2>/dev/null; then
    osascript -e "do shell script \"rm -rf /Applications/πD.app; cp -R '$TMP' /Applications/πD.app; xattr -cr /Applications/πD.app\" with administrator privileges" 2>/dev/null \
      && echo "installed → /Applications/πD.app (admin)" \
      || echo "note: could not write /Applications"
  fi
  rm -rf "$(dirname "$TMP")"
fi

mkdir -p "$HOME/Applications"
install_one "$HOME/Applications/πD.app"

# Direct double-click helper in project
cat >"$ROOT/Open πD.command" <<EOF
#!/bin/bash
cd "$ROOT" || exit 1
exec /bin/bash "$ROOT/scripts/mac-app-run.sh"
EOF
chmod +x "$ROOT/Open πD.command"

echo ""
echo "=== Test from Terminal (simulates Dock) ==="
env -i HOME="$HOME" USER="$USER" LOGNAME="${LOGNAME:-$USER}" TMPDIR="${TMPDIR:-/tmp}" \
  /bin/bash "$HOME/Applications/πD.app/Contents/MacOS/piD"
echo "exit code: $?"
echo ""
echo "Logs:"
echo "  ~/Library/Logs/piD.log"
echo "  ~/piD-launch.log"
echo ""
echo "Open app:"
echo "  open /Applications/πD.app"
echo ""
echo "Or double-click in project folder:"
echo "  Open πD.command"
